WITH CTE AS (
    SELECT 
    TRY_TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
     DATE(TRY_TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
     HOUR(TRY_TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

     CASE 
     WHEN DAYNAME(TRY_TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
     THEN 'WEEKEND'
     ELSE 'BUSINESSDAY'
     END AS DAY_TYPE,
     CASE 
     WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) in ('12','1','2')
     THEN 'WINTER'
     WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) in ('3','4','5')
     THEN 'SPRING'
     WHEN MONTH(TRY_TO_TIMESTAMP(STARTED_AT)) in ('6','7','8')
     THEN 'SUMMER'
     ELSE 'AUTHUM'
     END AS STATION_OF_YEAR


    FROM {{ source('demo', 'bike') }}
)
SELECT * FROM CTE